### ISSUE TITLE
Confusing term use

### ISSUE THREAD

**Issue by puttimeth** [2110336-SoftwareEngineering2/sec33_Kojira#104]
เนื่องจากระบบเรามีการเพิ่ม field exist เพื่อรองรับการ delete ซึ่งจะไม่ใช่การ delete จริงแต่เป็นการปิดการมองเห็น
และเรามีระบบ admin ที่สามารถลบข้อมูลจาก database ได้จริง ๆ ทำให้เกิดความสับสนในเรื่องของคำศัพท์ที่ใช้
จึงต้องการระดมความเห็นว่า**เราควรจะใช้ term อะไรกับการลบทั้งสองแบบ**
1.
การปิดการมองเห็นใช้ cancel eg. cancelNont cancelRoom
การลบออกจากฐานข้อมูลใช้ delete eg. deleteNont deleteReservation
2.
การปิดการมองเห็นใช้ delete eg. deleteNont deleteRoom
การลบออกจากฐานข้อมูลใช้ remove eg. removeNont removeReservation

หรือถ้ามี term ที่สร้างความเข้าใจได้ดีกว่านี้ขอให้เสนอมา

**Comment by Megacodexz** [comment]
คิดว่าแบบที่ 2 ดีกว่า
การปิดการมองเห็น user จะต้องเห็นคำนั้นใน front end ซึ่งคำว่า cancelNont cancelRoom มันดูแปลก ๆ
deleteNont deleteRoom user น่าจะเข้าใจได้ดีอยู่แล้ว ไม่ควรเปลี่ยน
ส่วนการลบออกจากฐานข้อมูล ผมว่า remove มันใช้ง่ายและก็สื่อความหมายได้ชัดเจน (แค่อย่าสับสนกันก็พอ)

**Comment by KombangkoeDias** [comment]
เห็นด้วยกับ @Megacodexz  cancel มันดูแปลกๆ delete กับ remove ดูโอเคกว่า
