### ISSUE TITLE
ถามความเห็นเกี่ยวกับ Ant Design component

### ISSUE THREAD

**Issue by puttimeth** [2110336-SoftwareEngineering2/sec33_Kojira#46]
เนื่องจากเรายังไม่มี import component จาก library ไหนเลย เลยไปค้นหาดูและพบตัวนี้
[Ant Design](https://ant.design/components/overview/)
เท่าที่ดูมี component หลากหลาย ตั้งแต่ Card, Modal, Input, TimePicker ซึ่งคิดว่ารองรับความต้องการของเราได้ในระดับหนึ่ง
และในเว็บยังมีตัวอย่างโค้ดและ API ประกอบมาด้วยทำให้ใช้งานได้ง่าย

เท่าที่ลองใช้งาน Popconfirm ใน Shelter Delete ได้ออกมาประมาณนี้
![image](https://user-images.githubusercontent.com/32786620/109259127-2cc70000-782e-11eb-86b4-e8b90e113d9d.png)
โดยการนำโค้ด Popconfirm component มาครอบของเก่า และสร้างฟังก์ชันเพื่อรองรับการทำงานของ Confirm button, cancel button เท่านั้น
![image](https://user-images.githubusercontent.com/32786620/109259213-5718bd80-782e-11eb-9f4f-f40e24f99599.png)
![image](https://user-images.githubusercontent.com/32786620/109259225-5c760800-782e-11eb-8bf6-832459ef0230.png)

จึงอยากสอบถามความคิดเห็นว่าเราจะใช้ library ตัวนี้กันดีไหม หรือว่ามีตัวอื่นที่ดีกว่านี้

**Comment by Megacodexz** [comment]
สวยดีอะ ชอบ ๆ ผมว่าใช้ได้ไม่มีปัญหาอะไร
รู้สึกโค้ดคล้าย ๆ reactstrap
แต่เนื่องจากตอนนี้เราใช้ Bootstrap อยู่ ถ้าจะใช้ Ant Design จะใช้แค่บางส่วนไหม หรือว่าเปลี่ยนทั้งหมดเลย

**Comment by puttimeth** [comment]
คิดว่าเลือกใช้เป็นบางชิ้นก็ได้ อย่างพวก layout ใช้ bootstrap มันก็ไม่ได้ยากอะไร เน้นเป็นตัวเสริมสำหรับ component ที่ขี้เกียจทำเองน่าจะดีกว่า

**Comment by Megacodexz** [comment]
รอความเห็น @KombangkoeDias แล้วกัน ผู้นี้น่าจะเคยลองมาเยอะ
ส่วนผมก็รู้สึกว่า... Ant Design ดูใช้สะดวกกว่าเยอะเลยอะ สวยกว่าด้วย ใช้ bootstrap ไปทำไมเนี่ย 555

**Comment by peaky2000** [comment]
เราใช้ component Modal จาก react-bootstrap ที่ใช้กับ delete ไปแล้วอะ555 พึ่งเห็นว่ามึคุยกันในนี้ด้วย

**Comment by peaky2000** [comment]
ถ้าสะดวกกว่า สวยกว่าใช้ Ant Design ก็ได้ หรือใครอยากใช้อะไรก็ได้มั้ง

**Comment by puttimeth** [comment]
ถ้าใช้ไปแล้วงั้นก็ใช้ bootstrap ไปดีกว่า อยากให้ทั้งระบบหน้าตาเหมือนกัน
