### ISSUE TITLE
Nont front-end inappropiate behavior

### ISSUE THREAD

**Issue by puttimeth** [2110336-SoftwareEngineering2/sec33_Kojira#59]
**Problem**: 
There's problem with router path
![image](https://user-images.githubusercontent.com/32786620/111027127-d27a9180-8420-11eb-87c3-cc6d6a62381e.png)
They use the same starter which is '/nont' and react-router-dom just take it all to show in the broswer as below.
![image](https://user-images.githubusercontent.com/32786620/111027151-fb9b2200-8420-11eb-8801-a11397288b75.png)
![image](https://user-images.githubusercontent.com/32786620/111027163-0eadf200-8421-11eb-8de4-9764e60c13ee.png)
![image](https://user-images.githubusercontent.com/32786620/111027168-14a3d300-8421-11eb-83e8-31813ffe982a.png)

**Solution**:
One of the possible way is to change path so that they have no duplicated part.
![image](https://user-images.githubusercontent.com/32786620/111027211-5c2a5f00-8421-11eb-98ab-caa47db18d76.png)

**Comment by peaky2000** [comment]
จะให้เปลี่ยน router path ไม่ให้ขึ้นด้วย nont เหมือนกันชะ หรือว่าตอนนี้เปลี่ยนแล้ว

**Comment by puttimeth** [comment]
ยัง ทำเลย
