### ISSUE TITLE
We need loading screen

### ISSUE THREAD

**Issue by puttimeth** [2110336-SoftwareEngineering2/sec33_Kojira#84]
ปัญหาคือเวลาเราเปิดหน้าใหม่ต้องมีการโหลดข้อมูลซึ่งใช้เวลาสักพักหนึ่ง เราจึงต้องการ loading screen ที่ทุกคนจะใช้ร่วมกัน

**Comment by Megacodexz** [comment]
โรเจอร์! จะไปทำงับ

**Comment by Megacodexz** [comment]
Added it in pull request #87
